<?php

use Illuminate\Database\Seeder;
use App\Auditory;
class AuditoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Auditory::create([
            'name'=>'201',
            'capacity'=>30,
            'type'=>1
        ]);
        Auditory::create([
            'name'=>'202',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'203',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'204',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'205',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'206',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'207',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'301',
            'capacity'=>80,
            'type'=>1
        ]);
        Auditory::create([
            'name'=>'302',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'303',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'304',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'305',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'401',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'402',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
            'name'=>'403',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
        'name'=>'404',
        'capacity'=>30,
        'type'=>2
    ]);
        Auditory::create([
        'name'=>'405',
        'capacity'=>30,
        'type'=>2
    ]);
        Auditory::create([
            'name'=>'406',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
        'name'=>'501',
        'capacity'=>30,
        'type'=>2
    ]);
        Auditory::create([
        'name'=>'502',
        'capacity'=>30,
        'type'=>2
    ]);
        Auditory::create([
            'name'=>'601',
            'capacity'=>30,
            'type'=>2
        ]);
        Auditory::create([
        'name'=>'602',
        'capacity'=>30,
        'type'=>2
    ]);
    }
}
